# Generated by Django 5.0 on 2023-12-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test_cases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qno', models.IntegerField()),
                ('question', models.CharField(max_length=100)),
                ('sinpu', models.CharField(max_length=100)),
                ('soutpu', models.CharField(max_length=100)),
                ('inpu', models.CharField(max_length=100)),
                ('outpu', models.CharField(max_length=100)),
                ('inpu2', models.CharField(max_length=100)),
                ('outpu2', models.CharField(max_length=100)),
                ('inpu3', models.CharField(max_length=100)),
                ('outpu3', models.CharField(max_length=100)),
                ('inpu4', models.CharField(max_length=100)),
                ('outpu4', models.CharField(max_length=100)),
            ],
        ),
    ]
