# Generated by Django 5.0 on 2023-12-10 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contestapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='test_cases',
            new_name='Questions',
        ),
    ]
