# Generated by Django 5.0 on 2023-12-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestapp', '0003_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
